### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by charlesmz** [electro-logic/Oscilloscope#2]
I don't understand this line of code in Channel.GetWaveform method：
A(V) = [(240 - <Raw_Byte>) * (<Volts_Div> / 25) - [(<Vert_Offset> + <Volts_Div> * 4.6)]]

Why should 240 be subtracted Raw_Byte, and 25 ？， 4.6 ？

**Comment by electro-logic** [comment]
Hello,
It's the oscilloscope formula to decode raw bytes and find the voltage. You can find it in the "DS1000E/D Waveform Data Formatting Guide" available on the manufacturer website.
