### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Elmue** [electro-logic/Oscilloscope#3]
Hello Leonardo

I was so happy to find this project. But sadly it does not work at all.
Your version 1.0 seems to be compiled wrongly:

![Image3](https://github.com/user-attachments/assets/afb03e18-7d00-4a8b-939a-b1ceeb7c2780)

And your version 1.1 does not show any USB device although my oscilloscope is connected.
It says: "Please connect an oscilloscope, then click Refresh"
I have a Rigol DS 1074, bought in 2020
I have installed UltraSigma and Rigol UltraScope and I can connect to the oscilloscope with their software.

**Comment by electro-logic** [comment]
Hello Elmue,

NI-VISA .NET Runtime 2023 Q2 is required to run the application, you can download it from http://www.ni.com/download/ni-visa-run-time-engine as described in the Readme.MD file

Please also ensure that your oscilloscope is updated with the latest firmware:
https://www.rigolna.com/firmware/?srsltid=AfmBOoq_qeRD72XTTnc8EWRJu8UwFlPRP0xS4nDxcu02himfztPn0XQX

Please let me know if you need further assistance or if I can close this issue.

Cheers,
Leonardo

**Comment by Elmue** [comment]
I have seen that.
But I will get no error at all if this is not installed ?
Just the USB devices are not listed but no error message to the user if it is not ????

I have to install one GIGABYTE to use your tiny application ?
Did you once study what of this huge NI installation is really necessary ?
Would it be possible to extract only the required files to make you app run with a reduced disk space?

**Comment by electro-logic** [comment]
Previous NI-VISA Runtime releases (ex. v5.4) were much smaller, but are not compatible with Windows 10/11.

Latest version 2024 Q4 contains additional items, but to run the application you need the NI-VISA .NET Runtime only. You can then uninstall any additional software.

![Screenshot 2024-12-10 232731](https://github.com/user-attachments/assets/591e0a2c-3a13-4852-9238-ea87db5a67f0)
