### ISSUE TITLE
Still an issue

### ISSUE THREAD

**Issue by Elmue** [electro-logic/Oscilloscope#4]
You closed my issue.

However it still is a severe programing error on your site that you do not display an error message if the NI framework is not installed.
You let the user with no detected oscilloscope although it is connected.
The user has no idea what is wrong.
I think you should fix this.

**Comment by electro-logic** [comment]
That's a good idea, please contribute with a pull request if you can

**Comment by electro-logic** [comment]
README and Release notes are now updated to better mention runtime requirements

**Comment by Elmue** [comment]
You changed the Readme but still there is no error message for the user.
Once again you closed the issue without fixing it.

Apart from that this project is completely useless for me.
I will not request from the users of my software that they install 1 GIGAbyte of nonsense on their disk with 7 services running permanently in the background!
This NI-VISA project is a total garbage.

One Gigabyte to just communicate with a USB device?
That is ridiculous.

I will will keep on searching for a useful project that is able to communicate DIRECTLY from my application over WinUSB to the oscilloscope. If such a project does not exist I will write it on my own.

**Comment by electro-logic** [comment]
Any PR (Pull Request) is welcome if you want to take part in the development and replace NI-VISA with something lighter.
